---
- include: firewall.yml

- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install openvpn
  apt:
    name: openvpn
    state: present

- name: create /etc/openvpn
  file:
    path: /etc/openvpn
    state: directory
    mode: 0755
    owner: root
    group: root

- name: create /etc/openvpn/keys
  file:
    path: /etc/openvpn/keys
    state: directory
    mode: 0700
    owner: root
    group: root

- name: create clientside and serverside directories
  file:
    path: "{{item}}"
    state: directory
    mode: 0755
  with_items:
    - "{{clientside}}/keys"
    - "{{serverside}}"
  become: true
  become_user: "{{user}}"

- name: create openvpn base client.conf
  template:
    src: client.conf.j2
    dest: "{{clientside}}/client.conf"
    owner: root
    group: root
    mode: 0644

- name: download EasyRSA
  get_url:
    url: "{{easyrsa_url}}"
    dest: "/home/{{user}}/openvpn"
  become: true
  become_user: "{{user}}"

- name: create scripts
  template:
    src: "{{item}}.j2"
    dest: "/home/{{user}}/openvpn/{{item}}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - create_serverside
    - create_clientside
  tags: client

- name: run serverside script
  command: ./create_serverside
  args:
    chdir: "/home/{{user}}/openvpn"
    creates: "{{easyrsa_server}}/ta.key"
  become: true
  become_user: "{{user}}"

- name: run clientside script
  command: ./create_clientside {{item}}
  args:
    chdir: "/home/{{user}}/openvpn"
    creates: "{{clientside}}/files/{{item}}.ovpn"
  become: true
  become_user: "{{user}}"
  with_items: "{{openvpn_clients}}"
  tags: client

- name: install all server keys
  command: install -o root -g root -m 600 {{item.name}} /etc/openvpn/keys/
  args:
    chdir: "{{item.path}}"
    creates: "/etc/openvpn/keys/{{item.name}}"
  with_items:
    - name: "ca.crt"
      path: "{{easyrsa_server}}/pki"
    - name: "{{ansible_hostname}}.crt"
      path: "{{easyrsa_server}}/pki/issued"
    - name: "{{ansible_hostname}}.key"
      path: "{{easyrsa_server}}/pki/private"
    - name: "ta.key"
      path: "{{easyrsa_server}}"

- name: copy Diffie-Hellman key
  copy:
    src: "{{openvpn_dh}}"
    dest: /etc/openvpn/keys/dh.pem
    owner: root
    group: root
    mode: 0600

- name: create openvpn server.conf
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
    owner: root
    group: root
    mode: 0644
  notify: restart openvpn

- name: start openvpn
  service:
    name: openvpn
    state: started
